### ISSUE TITLE
Error executing FreeMarker template

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CirceR#29]
I'm trying to use Capr to create a cohort definition, and render it through CirceR, but I get an error message I don't know what to do with:
```
Mar 29, 2023 9:38:05 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
When calling function "optionName", required parameter "id" (parameter #2) was specified, but had null/missing value.

----
Tip: If the parameter value expression on the caller side is known to be legally null/missing, you may want to specify a default value for it with the "!" operator, like paramValue!defaultValue.
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #function optionName(options, id)  [in template "utils.ftl" in function "optionName" at line 12, column 1]
	- Reached through: ${utils.optionName(inputTypes.groupTy...  [in template "criteriaTypes.ftl" in macro "GroupHeader" at line 256, column 32]
	- Reached through: @GroupHeader group=group  [in template "criteriaTypes.ftl" in macro "Group" at line 259, column 151]
	- Reached through: @ct.Group group=rule.expression  [in template "cohortExpression.ftl" at line 47, column 14]
----

Java stack trace (for programmers):
----
freemarker.core._MiscTemplateException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Macro$Context.checkParamsSetAndApplyDefaults(Macro.java:308)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:875)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.Environment.invokeFunction(Environment.java:828)
	at freemarker.core.MethodCall._eval(MethodCall.java:65)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:376)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:644)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at org.ohdsi.circe.cohortdefinition.printfriendly.MarkdownRender.renderCohort(MarkdownRender.java:43)
	at org.ohdsi.circe.cohortdefinition.printfriendly.MarkdownRender.renderCohort(MarkdownRender.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at RJavaTools.invokeMethod(RJavaTools.java:399)

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.RuntimeException: freemarker.core._MiscTemplateException: When calling function "optionName", required parameter "id" (parameter #2) was specified, but had null/missing value.

----
Tip: If the parameter value expression on the caller side is known to be legally null/missing, you may want to specify a default value for it with the "!" operator, like paramValue!defaultValue.
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #function optionName(options, id)  [in template "utils.ftl" in function "optionName" at line 12, column 1]
	- Reached through: ${utils.optionName(inputTypes.groupTy...  [in template "criteriaTypes.ftl" in macro "GroupHeader" at line 256, column 32]
	- Reached through: @GroupHeader group=group  [in template "criteriaTypes.ftl" in macro "Group" at line 259, column 151]
	- Reached through: @ct.Group group=rule.expression  [in template "cohortExpression.ftl" at line 47, column 14]
----
```

The R code for reproducing the error:
```r
library(Capr)
t2dm <- cs(
  descendants(443238, 201820, 442793), 
  descendants(exclude(195771, 201254, 435216, 761051, 4058243, 40484648)),
  name = "Type 2 diabetes mellitus (diabetes mellitus excluding T1DM and secondary)"
)
sitagliptin <- cs(
  descendants(1580747),
  name = "Sitagliptin"
)
sitagliptinNewUsers <- cohort(
  entry = entry(
    drug(sitagliptin),
    observationWindow = continuousObservation(priorDays = 365)
  ),
  attrition = attrition(
    "prior T2DM" = atLeast(1, condition(t2dm), duringInterval(eventStarts(-Inf, 0)))
  )
)
CirceR::cohortPrintFriendly(as.json(sitagliptinNewUsers))
```
Oddly enough, rendering to SQL works fine. Here's the JSON:
```json
{
  "ConceptSets": [
    {
      "id": 0,
      "name": "Sitagliptin",
      "expression": {
        "items": [
          {
            "concept": {
              "CONCEPT_ID": 1580747,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          }
        ]
      }
    },
    {
      "id": 1,
      "name": "Type 2 diabetes mellitus (diabetes mellitus excluding T1DM and secondary)",
      "expression": {
        "items": [
          {
            "concept": {
              "CONCEPT_ID": 443238,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 201820,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 442793,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 195771,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 201254,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 435216,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 761051,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 4058243,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 40484648,
              "CONCEPT_NAME": "",
              "STANDARD_CONCEPT": "",
              "STANDARD_CONCEPT_CAPTION": "",
              "INVALID_REASON": "",
              "INVALID_REASON_CAPTION": "",
              "CONCEPT_CODE": "",
              "DOMAIN_ID": "",
              "VOCABULARY_ID": "",
              "CONCEPT_CLASS_ID": ""
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          }
        ]
      }
    }
  ],
  "PrimaryCriteria": {
    "CriteriaList": [
      {
        "DrugExposure": {
          "CodesetId": 0
        }
      }
    ],
    "ObservationWindow": {
      "PriorDays": 365,
      "PostDays": 0
    },
    "PrimaryCriteriaLimit": {
      "Type": "First"
    }
  },
  "QualifiedLimit": {
    "Type": "First"
  },
  "ExpressionLimit": {
    "Type": "First"
  },
  "InclusionRules": [
    {
      "name": "prior T2DM",
      "expression": {
        "Criteria": {
          "ConditionOccurrence": {
            "CodesetId": 1
          }
        },
        "StartWindow": {
          "Start": {
            "Coeff": -1
          },
          "End": {
            "Days": 0,
            "Coeff": -1
          },
          "UseIndexEnd": false,
          "UseEventEnd": false
        },
        "Occurrence": {
          "Type": 2,
          "Count": 1
        }
      }
    }
  ],
  "CensoringCriteria": [],
  "CollapseSettings": {
    "CollapseType": "ERA",
    "EraPad": 0
  },
  "CensorWindow": {},
  "cdmVersionRange": ">=5.0.0"
}
```

**Comment by schuemie** [comment]
Now using `Capr::getConceptSetDetails()`, so we have concept information:
```json
{
  "ConceptSets": [
    {
      "id": 0,
      "name": "Sitagliptin",
      "expression": {
        "items": [
          {
            "concept": {
              "CONCEPT_ID": 1580747,
              "CONCEPT_NAME": "sitagliptin",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "593411",
              "DOMAIN_ID": "Drug",
              "VOCABULARY_ID": "RxNorm",
              "CONCEPT_CLASS_ID": "Ingredient"
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          }
        ]
      }
    },
    {
      "id": 1,
      "name": "Type 2 diabetes mellitus (diabetes mellitus excluding T1DM and secondary)",
      "expression": {
        "items": [
          {
            "concept": {
              "CONCEPT_ID": 443238,
              "CONCEPT_NAME": "Diabetic - poor control",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "268519009",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 201820,
              "CONCEPT_NAME": "Diabetes mellitus",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "73211009",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 442793,
              "CONCEPT_NAME": "Complication due to diabetes mellitus",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "74627003",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": false,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 195771,
              "CONCEPT_NAME": "Secondary diabetes mellitus",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "8801005",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 201254,
              "CONCEPT_NAME": "Type 1 diabetes mellitus",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "46635009",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 435216,
              "CONCEPT_NAME": "Disorder due to type 1 diabetes mellitus",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "420868002",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 761051,
              "CONCEPT_NAME": "Complication due to secondary diabetes mellitus",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "138811000119100",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 4058243,
              "CONCEPT_NAME": "Diabetes mellitus during pregnancy, childbirth and the puerperium",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "199223000",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          },
          {
            "concept": {
              "CONCEPT_ID": 40484648,
              "CONCEPT_NAME": "Type 1 diabetes mellitus uncontrolled",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "444073006",
              "DOMAIN_ID": "Condition",
              "VOCABULARY_ID": "SNOMED",
              "CONCEPT_CLASS_ID": "Clinical Finding"
            },
            "isExcluded": true,
            "includeDescendants": true,
            "includeMapped": false
          }
        ]
      }
    }
  ],
  "PrimaryCriteria": {
    "CriteriaList": [
      {
        "DrugExposure": {
          "CodesetId": 0
        }
      }
    ],
    "ObservationWindow": {
      "PriorDays": 365,
      "PostDays": 0
    },
    "PrimaryCriteriaLimit": {
      "Type": "First"
    }
  },
  "QualifiedLimit": {
    "Type": "First"
  },
  "ExpressionLimit": {
    "Type": "First"
  },
  "InclusionRules": [
    {
      "name": "prior T2DM",
      "expression": {
        "Criteria": {
          "ConditionOccurrence": {
            "CodesetId": 1
          }
        },
        "StartWindow": {
          "Start": {
            "Coeff": -1
          },
          "End": {
            "Days": 0,
            "Coeff": -1
          },
          "UseIndexEnd": false,
          "UseEventEnd": false
        },
        "Occurrence": {
          "Type": 2,
          "Count": 1
        }
      }
    }
  ],
  "CensoringCriteria": [],
  "CollapseSettings": {
    "CollapseType": "ERA",
    "EraPad": 0
  },
  "CensorWindow": {},
  "cdmVersionRange": ">=5.0.0"
}
```
Still throwing same error

**Comment by chrisknoll** [comment]
Ok, thanks for the json, I can wrap a test around it and see what's up.

**Comment by schuemie** [comment]
I apparently wasn't using Capr correctly. Including correct Capr code here for future reference:

```r
library(Capr)
t2dm <- cs(
  descendants(443238, 201820, 442793), 
  descendants(exclude(195771, 201254, 435216, 761051, 4058243, 40484648)),
  name = "Type 2 diabetes mellitus (diabetes mellitus excluding T1DM and secondary)"
)
sitagliptin <- cs(
  descendants(1580747),
  name = "Sitagliptin"
)
sitagliptinNewUsers <- cohort(
  entry = entry(
    drug(sitagliptin),
    primaryCriteriaLimit = "First",
    observationWindow = continuousObservation(priorDays = 365)
  ),
  attrition = attrition(
      "prior T2DM" = withAll(
        atLeast(1, condition(t2dm), duringInterval(eventStarts(-Inf, 0)))
      )
  ),
  exit = exit(endStrategy = drugExit(sitagliptin, persistenceWindow = 30, surveillanceWindow = 0))
)
```
